## Driver Parameters
Id: 32
obs_veh_num: 4
radius_disks: 1.11803
Length: 4
Width: 2
## initial state
init_state: [27, -15, 3]
init_obs: [53, 8, 3.14, 3 , 0 , 0]

n_points_spline: 100
N_SPLINE_POINTS: 30
Acc: 2

## ref path
x_A_0 : [53, 0]
y_A_0 : [8, 8]
theta_A_0: [3.14, 3.14]
x_A_1 : [53, 30, 23, 23]
y_A_1 : [8, 8, 0, -50]
theta_A_1: [3.14, 3.14, -1.72, -1.72]

driving_style: "Constant"