## Driver Parameters
Id: 31
obs_veh_num: 4
radius_disks: 1.11803
Length: 4
Width: 2
## initial state
init_state: [27, -15, 3]
init_obs: [53, 8, 1.72, 3 , 1 , 0]

n_points_spline: 100
N_SPLINE_POINTS: 30
Acc: 2

## ref path
x_A_0 : [53, 30]
y_A_0 : [8, 8]
theta_A_0: [3.14, 3.14]
x_A_1 : [53, 30, 23, 23]
y_A_1 : [8, 8, 0, -50]
theta_A_1: [3.14, 3.14, -1.72, -1.72]

##Topics
state_topic: "state_A_1"
action_topic: "action_1"
vis_topic: "/visualization_marker"
sensor_data_topic: "sensor2"

root_frame: "map"
agent_frame_id: "agent2"
robot_frame_id: "base_link"

driving_style: "Constant"
color: [1, 0, 1, 1]